version: '3.9'
services:

  wordpres_app:
    image: wordpress:4.9.4-php7.2-apache
    container_name: wordpress_web
    environment:
      - WORDPRESS_DB_HOST=mariadb_host
      - WORDPRESS_DB_USER=adedb_user
      - WORDPRESS_DB_PASSWORD=hello123
      - WORDPRESS_DB_NAME=wpress_db
    ports:
      - 8080:80
    volumes:
      - worpress_app:/var/www/html
    networks:
      - my_netwk_wdpress
    depends_on:
      - mariadb_host

  
  mariadb_host:
    image: mariadb:10.4.12
    container_name: mariadb_host
    environment:
      - MYSQL_ROOT_PASSWORD=hello123
      - MYSQL_DATABASE=wpress_db

      - MYSQL_USER=adedb_user
      - MYSQL_PASSWORD=hello123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_netwk_wdpress

volumes:
  worpress_app:
  db_data:


networks: 
  my_netwk_wdpress:
    driver: bridge